'use client';

import { useState, useRef } from "react";
const DIETS=[{id:"none",label:"제한 없음",emoji:"🍽️"},{id:"vegetarian",label:"채식",emoji:"🥦"},{id:"lowcarb",label:"저탄고지",emoji:"🥩"},{id:"diet",label:"다이어트",emoji:"⚖️"}];
const HH=[{id:"1",label:"1인",emoji:"🧑"},{id:"2",label:"2인",emoji:"👫"},{id:"4",label:"가족(3-4인)",emoji:"👨‍👩‍👧"}];
const COOK=[{id:"minimal",label:"간단하게",emoji:"⚡",desc:"15분 이내, 조립 위주"},{id:"moderate",label:"보통",emoji:"🍳",desc:"30분, 제대로 요리"},{id:"ambitious",label:"요리 좋아해요",emoji:"👨‍🍳",desc:"45분+, 본격 요리"}];
const SPRING_PRODUCE="봄 제철: 냉이, 달래, 두릅, 취나물, 미나리, 봄동, 쑥, 딸기, 매실, 봄 양배추";
const MEALS={none:{minimal:{breakfasts:[{name:"아보카도 토스트 + 계란",time:"5분",cal:350,protein:"14g",seasonal:["달걀"],ing:["식빵 1장","아보카도 반 개","달걀 1개","소금 약간","후추 약간"],how:"토스트 굽기. 아보카도 으깨서 올리기. 프라이 또는 반숙 얹기."},{name:"그릭요거트 과일 파르페",time:"3분",cal:320,protein:"18g",seasonal:["딸기"],ing:["그릭요거트 200g","그래놀라 3큰술","딸기 5-6알","꿀 1작은술"],how:"요거트, 그래놀라, 딸기 순서로 레이어. 꿀 뿌리기."},{name:"참치 주먹밥",time:"10분",cal:380,protein:"20g",seasonal:[],ing:["밥 1공기","참치캔 1개 (작은것)","마요네즈 1큰술","김 2장","깨 약간"],how:"참치+마요 섞기. 밥에 넣고 삼각형으로 뭉치기. 김 감싸기."},{name:"바나나 땅콩버터 스무디",time:"3분",cal:400,protein:"16g",seasonal:[],ing:["바나나 1개","땅콩버터 2큰술","우유 200ml","오트밀 3큰술"],how:"전부 블렌더에 갈기."}],
lunches:[{name:"봄동 비빔밥",time:"15분",cal:450,protein:"18g",seasonal:["봄동","달래"],ing:["밥 1공기","봄동 한 줌 (50g)","달래 한 줌 (30g)","고추장 1큰술","참기름 1작은술","계란 1개","당근 1/4개"],how:"봄동, 달래, 당근 손질. 밥 위에 올리고 계란 프라이 얹기. 고추장+참기름."},{name:"닭가슴살 샐러드 랩",time:"10분",cal:380,protein:"28g",seasonal:["봄 양배추"],ing:["또띠아 1장","닭가슴살 100g(삶은것)","양배추 한 줌","당근 1/4개","소스 2큰술"],how:"닭가슴살 찢기. 채소와 소스 넣고 말기."},{name:"미나리 된장국 + 주먹밥",time:"12분",cal:350,protein:"15g",seasonal:["미나리"],ing:["된장 1큰술","미나리 한 줌 (40g)","두부 1/4모","파 1대","멸치육수 2컵","밥 1공기"],how:"멸치육수에 된장 풀기. 두부, 미나리 넣고 끓이기. 주먹밥과 함께."},{name:"참치김치볶음밥",time:"10분",cal:420,protein:"22g",seasonal:[],ing:["밥 1공기","참치캔 1개","김치 1/2컵 (썰어서)","계란 1개","참기름 1작은술","김가루 약간"],how:"팬에 김치 볶다가 참치, 밥 넣고 볶기. 계란 프라이 올리고 김가루."}],
dinners:[{name:"봄나물 제육볶음",time:"15분",cal:480,protein:"28g",seasonal:["취나물","미나리"],ing:["돼지고기 앞다리살 300g","고추장 1.5큰술","고춧가루 1큰술","간장 1큰술","설탕 1큰술","다진 마늘 0.5큰술","양파 반 개","취나물 한 줌","밥 1공기"],how:"양념장 섞기(고추장+고춧가루+간장+설탕+마늘). 고기에 버무려 10분 재우기. 팬에 기름 두르고 고기 볶기 8분. 양파 넣고 2분 더. 봄나물 곁들이기."},{name:"연어 미나리 덮밥",time:"12분",cal:500,protein:"32g",seasonal:["미나리"],ing:["연어 1토막 (150g)","미나리 한 줌 (40g)","밥 1공기","간장 1큰술","와사비 콩알만큼","아보카도 반 개","참기름 1작은술"],how:"연어 소금+후추 뿌려 팬에 4분씩 굽기. 밥 위에 미나리, 연어, 아보카도. 간장+와사비+참기름 섞어 뿌리기."},{name:"순두부찌개 + 밥",time:"15분",cal:380,protein:"22g",seasonal:["쪽파"],ing:["순두부 1봉지 (350g)","김치 1/2컵 (한 줌 썰어서)","돼지고기 다짐육 3큰술 (약 50g)","계란 1개","쪽파 2대","고춧가루 1.5큰술","참기름 1큰술","다진 마늘 1큰술","간장 1큰술","물 200ml","밥 1공기"],how:"뚝배기에 참기름+파+고기 볶기. 김치, 마늘, 고춧가루 넣고 1분 볶기. 물+간장 넣고 끓이기. 순두부 넣고 5분. 계란 톡 깨넣고 쪽파 올리기."},{name:"원팬 닭볶음탕",time:"15분 준비",cal:520,protein:"34g",seasonal:["감자","당근"],ing:["닭 4-5조각 (약 500g)","감자 1개","당근 반 개","양파 반 개","고추장 2큰술","간장 2큰술","고춧가루 1큰술","설탕 1큰술","다진 마늘 1큰술","물 1.5컵"],how:"닭+감자+당근+양파 냄비에 넣기. 양념장(고추장+간장+고춧가루+설탕+마늘) 섞어 붓기. 물 넣고 센불에 끓이다 중불로 25분. 중간에 한 번 뒤집기."}]},
moderate:{breakfasts:[{name:"봄나물 프리타타",time:"25분",cal:340,protein:"22g",seasonal:["달래","쑥"],ing:["달걀 8개","달래 한 줌 (30g)","쑥 한 줌 (30g)","슈레드 치즈 1/2컵 (50g)","올리브오일 1큰술"],how:"달래, 쑥 볶기. 달걀 풀어 붓기. 치즈 올리고 오븐 200도 15분."},{name:"딸기 리코타 토스트",time:"10분",cal:360,protein:"14g",seasonal:["딸기"],ing:["두꺼운 식빵 2장","리코타치즈 3큰술 (60g)","딸기 5-6알","꿀 1작은술","민트잎 2-3장"],how:"두꺼운 토스트에 리코타 바르기. 딸기 올리고 꿀, 민트."},{name:"시금치 계란 볶음밥",time:"10분",cal:400,protein:"20g",seasonal:["시금치"],ing:["밥 1공기","시금치 한 줌 (50g)","계란 2개","참기름 1작은술","소금 약간"],how:"시금치 볶다가 밥 넣고 볶기. 계란 스크램블 섞기. 참기름."}],
lunches:[{name:"냉이 된장찌개",time:"25분",cal:320,protein:"16g",seasonal:["냉이"],ing:["냉이 한 줌 (50g)","된장 1.5큰술","두부 1/2모 (150g)","감자 1개","호박 1/4개","멸치육수 3컵 (600ml)"],how:"멸치육수에 감자, 호박 끓이기. 된장 풀고 두부, 냉이 넣기."},{name:"봄 비빔국수",time:"15분",cal:420,protein:"15g",seasonal:["열무","오이"],ing:["소면 1인분 (100g)","열무김치 1/2컵","오이 1/2개","고추장 1.5큰술","식초 1큰술","설탕 0.5큰술","깨 약간"],how:"소면 삶아 찬물에 헹구기. 양념장 만들어 비비기. 열무김치, 오이 올리기."},{name:"두릅 삼겹살 구이",time:"20분",cal:500,protein:"24g",seasonal:["두릅"],ing:["삼겹살 200g","두릅 8-10개 (100g)","쌈장 2큰술","상추 5-6장","마늘 3-4쪽"],how:"삼겹살 구워서 두릅과 함께 상추쌈. 쌈장 필수!"}],
dinners:[{name:"봄 해물파전",time:"25분",cal:450,protein:"22g",seasonal:["쪽파"],ing:["쪽파 10대 (100g)","해물믹스 1컵 (150g)","부침가루 1컵 (100g)","달걀 2개","물 3/4컵","간장 1큰술","식초 0.5큰술","고춧가루 약간"],how:"부침가루+물+달걀 반죽. 쪽파 길게, 해물 올리고 부치기. 양념장과."},{name:"미나리 삼겹살 찜",time:"30분",cal:520,protein:"30g",seasonal:["미나리"],ing:["삼겹살 300g","미나리 1단 (100g)","마늘 5쪽","된장 1큰술","고추 1-2개"],how:"삼겹살 삶기. 된장 양념 만들기. 미나리와 함께 찜 또는 쌈으로."},{name:"봄 닭개장",time:"30분",cal:480,protein:"32g",seasonal:["취나물","미나리"],ing:["닭가슴살 200g","취나물 한 줌 (50g)","미나리 한 줌 (50g)","고춧가루 2큰술","다진 마늘 1큰술","대파 1대","밥 1공기","물 4컵"],how:"닭 삶아 찢기. 육수에 양념하고 나물 넣어 끓이기. 밥과 함께."}]}
},
vegetarian:{minimal:{breakfasts:[{name:"아보카도 김밥",time:"10분",cal:350,protein:"10g",seasonal:[],ing:["밥 1공기","아보카도 반 개","당근 1/4개","오이 1/4개","김 2장","참기름 1작은술"],how:"밥에 참기름 섞기. 김 위에 밥, 아보카도, 당근, 오이 올리고 말기."},{name:"두유 스무디볼",time:"5분",cal:320,protein:"14g",seasonal:["딸기"],ing:["두유 200ml","바나나 1개","딸기 5알","그래놀라 3큰술","치아씨드 1작은술"],how:"두유+바나나+딸기 갈기. 볼에 담고 그래놀라, 치아씨드 올리기."},{name:"계란 토스트",time:"5분",cal:340,protein:"16g",seasonal:[],ing:["식빵 2장","계란 2개","버터 1작은술","소금 약간"],how:"팬에 버터 녹이고 계란 프라이. 토스트에 올리기."}],lunches:[{name:"비빔밥 (채소)",time:"15분",cal:420,protein:"15g",seasonal:["봄동","시금치","당근"],ing:["밥 1공기","시금치 한 줌 (50g)","당근 1/4개","봄동 2-3장","고추장 1큰술","참기름 1작은술","계란 1개"],how:"채소 각각 데치기/볶기. 밥 위에 올리고 고추장, 참기름, 계란."},{name:"두부 김치찌개",time:"12분",cal:350,protein:"18g",seasonal:["쪽파"],ing:["두부 1/2모 (150g)","김치 1컵 (150g)","쪽파 2대","고춧가루 0.5큰술","참기름 1작은술","밥 1공기"],how:"김치 볶다가 물 붓기. 두부 넣고 끓이기. 쪽파 올리기."},{name:"봄나물 유부초밥",time:"15분",cal:380,protein:"12g",seasonal:["미나리","달래"],ing:["유부 8장","밥 1.5공기","미나리 한 줌 (30g)","달래 한 줌 (20g)","식초 2큰술","설탕 1큰술","깨 1작은술"],how:"밥에 식초, 설탕, 깨 섞기. 유부에 채우고 미나리, 달래 곁들이기."}],dinners:[{name:"된장찌개 + 봄나물 반찬",time:"15분",cal:380,protein:"16g",seasonal:["미나리","냉이"],ing:["된장 1.5큰술","두부 1/2모 (150g)","감자 1개","호박 1/4개","미나리 한 줌 (40g)","밥 1공기","멸치육수 3컵"],how:"멸치육수에 된장 풀기. 감자, 호박, 두부 넣고 끓이기. 봄나물 반찬과."},{name:"두부 스테이크 + 봄동 샐러드",time:"12분",cal:400,protein:"20g",seasonal:["봄동"],ing:["두부 1모 (300g)","간장 1큰술","올리브오일 1큰술","봄동 3-4장","참깨드레싱 2큰술"],how:"두부 두껍게 썰어 팬에 굽기. 간장 소스. 봄동 샐러드 곁들이기."},{name:"채소 잡채",time:"15분",cal:420,protein:"12g",seasonal:["시금치","당근"],ing:["당면 100g","시금치 한 줌 (50g)","당근 1/3개","양파 반 개","버섯 한 줌 (50g)","간장 2큰술","참기름 1큰술"],how:"당면 삶기. 채소 각각 볶기. 간장+참기름으로 비비기."}]},moderate:{breakfasts:[{name:"봄나물 프리타타",time:"25분",cal:340,protein:"22g",seasonal:["달래","쑥"],ing:["달걀 8개","달래 한 줌 (30g)","쑥 한 줌 (30g)","슈레드 치즈 1/2컵 (50g)","올리브오일 1큰술"],how:"달래, 쑥 볶기. 달걀 풀어 붓기. 치즈 올리고 오븐 200도 15분."},{name:"두부 스크램블 볶음밥",time:"15분",cal:380,protein:"18g",seasonal:["시금치"],ing:["두부 1/2모 (150g)","밥 1공기","시금치 한 줌 (50g)","양파 1/4개","간장 1큰술","참기름 1작은술"],how:"두부 으깨서 볶기. 양파, 시금치 넣고 밥 볶기. 간장, 참기름."}],lunches:[{name:"냉이 된장찌개",time:"25분",cal:320,protein:"16g",seasonal:["냉이"],ing:["냉이 한 줌 (50g)","된장 1.5큰술","두부 1/2모 (150g)","감자 1개","호박 1/4개","멸치육수 3컵 (600ml)"],how:"멸치육수에 감자, 호박 끓이기. 된장 풀고 두부, 냉이 넣기."},{name:"봄 비빔국수",time:"15분",cal:420,protein:"15g",seasonal:["열무","오이"],ing:["소면 1인분 (100g)","열무김치 1/2컵","오이 1/2개","고추장 1.5큰술","식초 1큰술","설탕 0.5큰술","깨 약간"],how:"소면 삶아 찬물에 헹구기. 양념장 비비기."}],dinners:[{name:"봄 채소파전",time:"25분",cal:380,protein:"14g",seasonal:["쪽파"],ing:["쪽파 8대 (80g)","호박 1/4개","당근 1/4개","부침가루 1컵 (100g)","달걀 2개","물 3/4컵","간장 1큰술"],how:"부침가루+물+달걀 반죽. 쪽파, 호박, 당근 올리고 부치기."},{name:"순두부찌개 (고기 없이)",time:"15분",cal:320,protein:"18g",seasonal:["쪽파"],ing:["순두부 1봉지 (350g)","김치 1/2컵","버섯 한 줌 (50g)","계란 1개","쪽파 2대","고춧가루 1큰술"],how:"김치, 버섯 볶기. 물 붓고 순두부 넣기. 계란, 쪽파."}]}},
lowcarb:{minimal:{breakfasts:[{name:"계란 2개 + 아보카도",time:"5분",cal:380,protein:"18g",seasonal:[],ing:["계란 2개","아보카도 반 개","소금 약간","후추 약간"],how:"계란 프라이 또는 스크램블. 아보카도 반 개와 함께."},{name:"그릭요거트 + 견과류",time:"3분",cal:300,protein:"20g",seasonal:[],ing:["그릭요거트 200g","아몬드 10알","호두 3개","시나몬 약간"],how:"요거트에 견과류, 시나몬 올리기."},{name:"삶은 달걀 + 닭가슴살",time:"5분",cal:320,protein:"30g",seasonal:[],ing:["삶은 달걀 2개","닭가슴살 1팩 (100g, 기성품)","샐러드 채소 한 줌"],how:"편의점 닭가슴살+삶은 달걀. 채소 곁들이기."}],lunches:[{name:"삼겹살 쌈",time:"12분",cal:450,protein:"24g",seasonal:["봄동"],ing:["삼겹살 200g","봄동 3-4장","상추 5장","쌈장 2큰술","마늘 3쪽","고추 1개"],how:"삼겹살 구워서 봄동, 상추에 쌈. 쌈장 필수."},{name:"닭가슴살 샐러드",time:"10분",cal:350,protein:"32g",seasonal:["봄 양배추"],ing:["닭가슴살 150g","양배추 2컵 (100g)","방울토마토 5-6개","올리브오일 1큰술","레몬즙 1큰술"],how:"닭가슴살 굽거나 삶아서 찢기. 채소 위에 올리고 드레싱."},{name:"두부 스테이크",time:"10분",cal:280,protein:"18g",seasonal:[],ing:["두부 1모 (300g)","간장 1큰술","올리브오일 1큰술","깨 약간","채소 한 줌"],how:"두부 팬에 바삭하게. 간장 소스. 채소 곁들이기."}],dinners:[{name:"고등어 구이 + 봄나물",time:"15분",cal:420,protein:"28g",seasonal:["미나리"],ing:["고등어 1마리 (토막)","소금 약간","미나리 한 줌 (50g)","무 한 토막 (100g)","간장 1큰술"],how:"고등어 소금 뿌려 팬/그릴에 굽기. 미나리 무침 곁들이기."},{name:"소고기 미나리 샤부샤부",time:"15분",cal:400,protein:"30g",seasonal:["미나리","봄동"],ing:["소고기 샤부용 200g","미나리 1/2단 (50g)","봄동 3-4장","버섯 한 줌 (50g)","폰즈소스 3큰술"],how:"육수 끓여서 소고기, 미나리, 봄동, 버섯 데치기. 폰즈소스에."},{name:"닭볶음탕 (밥 없이)",time:"15분",cal:380,protein:"34g",seasonal:["당근"],ing:["닭 4-5조각 (약 500g)","당근 반 개","양파 반 개","고추장 2큰술","간장 2큰술","다진 마늘 1큰술"],how:"감자 빼고 만들기. 닭+당근+양파+양념 끓이기."}]},moderate:{breakfasts:[{name:"계란 머핀 (미리 만들기)",time:"25분",cal:240,protein:"20g",seasonal:["시금치"],ing:["계란 6개","시금치 한 줌 (50g)","파프리카 1/4개","슈레드 치즈 3큰술","소금 약간"],how:"머핀틀에 계란+채소+치즈 넣고 180도 20분. 일주일치 만들기!"},{name:"아보카도 에그 보트",time:"15분",cal:350,protein:"16g",seasonal:[],ing:["아보카도 1개","계란 2개","소금 약간","후추 약간","슈레드 치즈 1큰술"],how:"아보카도 반으로 갈라 씨 빼기. 계란 깨넣고 오븐 200도 15분."}],lunches:[{name:"불고기 쌈밥",time:"20분",cal:420,protein:"28g",seasonal:["봄동"],ing:["소고기 불고기용 200g","봄동 4-5장","상추 5장","쌈장 2큰술","마늘 3쪽"],how:"소고기 양념 구이. 봄동, 상추에 쌈으로."},{name:"미나리 닭가슴살 샐러드",time:"15분",cal:350,protein:"30g",seasonal:["미나리"],ing:["닭가슴살 150g","미나리 한 줌 (50g)","방울토마토 5-6개","발사믹 드레싱 2큰술","올리브오일 1큰술"],how:"닭가슴살 구워 슬라이스. 미나리 샐러드 위에 올리기."}],dinners:[{name:"갈비찜 (감자 없이)",time:"30분",cal:480,protein:"32g",seasonal:["무"],ing:["갈비 500g","무 한 토막 (150g)","당근 반 개","간장 3큰술","설탕 1작은술","다진 마늘 1큰술"],how:"갈비 삶아 기름 제거. 양념장+무+당근과 끓이기."},{name:"해물탕",time:"25분",cal:350,protein:"28g",seasonal:["미나리","쪽파"],ing:["새우 5-6마리","조개 1컵 (150g)","오징어 1/2마리","미나리 한 줌 (40g)","쪽파 3대","고춧가루 1큰술","다진 마늘 1큰술","물 3컵"],how:"육수 끓여서 해물 넣기. 미나리, 쪽파 올리기."}]}},
diet:{minimal:{breakfasts:[{name:"오트밀 + 딸기",time:"5분",cal:280,protein:"10g",seasonal:["딸기"],ing:["오트밀 1/2컵 (40g)","물 또는 우유 200ml","딸기 4-5알","꿀 0.5작은술"],how:"오트밀에 물/우유 붓고 전자레인지 2분. 딸기, 꿀."},{name:"삶은 달걀 2개 + 방울토마토",time:"5분",cal:220,protein:"14g",seasonal:[],ing:["삶은 달걀 2개","방울토마토 6-7개"],how:"미리 삶아둔 달걀 + 방울토마토. 가장 간단한 아침."},{name:"바나나 + 땅콩버터 1스푼",time:"2분",cal:250,protein:"8g",seasonal:[],ing:["바나나 1개","땅콩버터 1큰술"],how:"바나나에 땅콩버터 찍어 먹기. 끝."}],lunches:[{name:"닭가슴살 포케볼 (소량 밥)",time:"10분",cal:380,protein:"28g",seasonal:["오이"],ing:["닭가슴살 100g","밥 반 공기","오이 1/3개","당근 1/4개","간장소스 1큰술"],how:"닭가슴살 썰기. 밥 반공기 위에 채소와 함께. 간장소스."},{name:"곤약 비빔면",time:"10분",cal:180,protein:"8g",seasonal:["오이"],ing:["곤약면 1봉지 (200g)","오이 1/2개","고추장 1큰술","식초 1큰술","깨 약간"],how:"곤약면 헹구기. 양념장 비비기. 오이 올리기. 초저칼로리!"},{name:"미나리 두부 샐러드",time:"10분",cal:250,protein:"16g",seasonal:["미나리"],ing:["두부 1/2모 (150g)","미나리 한 줌 (40g)","방울토마토 5-6개","참깨드레싱 2큰술"],how:"두부 깍둑썰기. 미나리, 토마토와 섞기. 드레싱 뿌리기."}],dinners:[{name:"닭가슴살 야채볶음",time:"12분",cal:320,protein:"30g",seasonal:["봄 양배추"],ing:["닭가슴살 150g","양배추 2컵 (100g)","파프리카 1/2개","양파 1/4개","간장 1큰술","올리브오일 1큰술"],how:"닭가슴살 볶기. 채소 넣고 간장으로 간. 밥 없이 또는 반공기."},{name:"된장찌개 (밥 적게)",time:"15분",cal:280,protein:"16g",seasonal:["미나리"],ing:["된장 1.5큰술","두부 1/2모 (150g)","호박 1/4개","미나리 한 줌 (30g)","밥 반 공기","멸치육수 2.5컵"],how:"된장찌개 끓이기. 밥은 반공기만."},{name:"연어 샐러드",time:"10분",cal:350,protein:"26g",seasonal:["봄 양배추"],ing:["연어 1토막 (150g)","양배추 2컵 (100g)","아보카도 반 개","레몬즙 1큰술","올리브오일 1큰술"],how:"연어 팬에 굽기. 채소 위에 올리고 레몬+올리브오일 드레싱."}]},moderate:{breakfasts:[{name:"시금치 오믈렛",time:"10분",cal:280,protein:"20g",seasonal:["시금치"],ing:["계란 3개","시금치 한 줌 (50g)","양파 1/4개","소금 약간","올리브오일 1작은술"],how:"시금치, 양파 볶기. 계란 풀어 붓기. 접어서 완성."},{name:"고구마 + 닭가슴살",time:"15분",cal:320,protein:"24g",seasonal:[],ing:["고구마 반 개 (100g)","닭가슴살 100g","샐러드 채소 한 줌"],how:"고구마 찜. 닭가슴살 구워서 함께."}],lunches:[{name:"봄동 닭가슴살 쌈",time:"15분",cal:320,protein:"28g",seasonal:["봄동"],ing:["닭가슴살 150g","봄동 4-5장","쌈장 2큰술","마늘 3쪽","고추 1개"],how:"닭가슴살 구워 슬라이스. 봄동에 쌈장과 쌈."},{name:"곤약 냉면",time:"15분",cal:220,protein:"10g",seasonal:["오이"],ing:["곤약면 1봉지 (200g)","오이 1/2개","삶은 달걀 1개","육수 1컵","식초 1큰술","겨자 약간"],how:"곤약면+차가운 육수. 오이, 달걀 올리기."}],dinners:[{name:"닭가슴살 미나리 볶음",time:"15분",cal:300,protein:"28g",seasonal:["미나리"],ing:["닭가슴살 150g","미나리 한 줌 (50g)","마늘 3쪽","간장 1큰술","참기름 1작은술"],how:"닭가슴살 볶다가 미나리, 마늘 넣기. 간장+참기름."},{name:"두부 스테이크 + 채소",time:"15분",cal:280,protein:"18g",seasonal:["봄동"],ing:["두부 1모 (300g)","봄동 3-4장","파프리카 1/2개","간장 1큰술"],how:"두부 팬에 굽기. 봄동, 파프리카 곁들이기. 간장소스."}]}}
};
function getMeals(d,c){return MEALS[d]?.[c]||MEALS.none?.minimal||{breakfasts:[],lunches:[],dinners:[]};}
function genWeek(meals){const days=["월","화","수","목","금","토","일"];const{breakfasts:b=[],lunches:l=[],dinners:d=[]}=meals;return days.map((day,i)=>({day,breakfast:b[i%b.length],lunch:l[i%l.length],dinner:d[i%d.length]}));}
function buildGrocery(wp){const all={};wp.forEach(d=>{[d.breakfast,d.lunch,d.dinner].forEach(m=>{m?.ing?.forEach(i=>{const k=i.toLowerCase();all[k]=(all[k]||0)+1;});});});return Object.entries(all).sort((a,b)=>b[1]-a[1]).map(([n,c])=>({name:n,count:c}));}
export default function MealPrepKR(){const[diet,sD]=useState("");const[hh,sH]=useState("");const[cook,sC]=useState("");const[wp,sW]=useState(null);const[gl,sG]=useState([]);const[ed,sE]=useState({});const[ch,sCh]=useState({});const[sg,sSg]=useState(false);const ref=useRef(null);
const downloadPDF = (element, filename) => {
  import('html2pdf.js').then((html2pdfModule) => {
    const html2pdf = html2pdfModule.default;
    html2pdf().set({
      margin: [10, 10, 10, 10],
      filename: filename,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { scale: 2, useCORS: true },
      jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
    }).from(element).save();
  });
};
const gen=()=>{const m=getMeals(diet,cook);const w=genWeek(m);sW(w);sG(buildGrocery(w));sCh({});sE({"월": true});sSg(false);setTimeout(()=>ref.current?.scrollIntoView({behavior:"smooth"}),150);};
const ok=diet&&hh&&cook;
return(<div style={{minHeight:"100vh",background:"linear-gradient(160deg,#e8f5e9 0%,#fffde7 30%,#fff3e0 60%,#fce4ec 100%)",fontFamily:"'Noto Sans KR',sans-serif",overflow:"hidden"}}><link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@400;600;700;800&family=Jua&display=swap" rel="stylesheet"/>
<div style={{maxWidth:780,margin:"0 auto",padding:"32px 20px",position:"relative",zIndex:1}}>
<div style={{textAlign:"center",marginBottom:36}}><div style={{fontSize:44,marginBottom:8}}>🥗🍓🌿</div><h1 style={{fontFamily:"'Jua',cursive",fontSize:"clamp(26px,5vw,38px)",color:"#e65100",margin:"0 0 8px"}}>봄 식단 플래너</h1><p style={{color:"#ff8a65",fontSize:15,margin:0,fontWeight:600}}>제철 재료로 일주일 식단, 결정 피로 제로!</p></div>
<div style={{background:"rgba(255,255,255,0.85)",borderRadius:16,padding:"16px 20px",marginBottom:20,border:"2px solid #c8e6c9"}}><div style={{fontWeight:800,color:"#2e7d32",fontSize:14,marginBottom:6}}>🌱 {SPRING_PRODUCE}</div></div>
<S n="1" t="식단 유형?" c="#e65100"><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(130px,1fr))",gap:10}}>{DIETS.map(x=>(<B key={x.id} a={diet===x.id} o={()=>sD(x.id)} c="#e65100"><div style={{fontSize:22}}>{x.emoji}</div><div style={{fontWeight:700,fontSize:12}}>{x.label}</div></B>))}</div></S>
<S n="2" t="몇 인분?" c="#e65100"><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:10}}>{HH.map(x=>(<B key={x.id} a={hh===x.id} o={()=>sH(x.id)} c="#e65100"><div style={{fontSize:22}}>{x.emoji}</div><div style={{fontWeight:800,fontSize:13}}>{x.label}</div></B>))}</div></S>
<S n="3" t="요리 수준?" c="#e65100">{COOK.map(x=>(<B key={x.id} a={cook===x.id} o={()=>sC(x.id)} c="#e65100" w><span style={{fontSize:22,marginRight:12}}>{x.emoji}</span><div><div style={{fontWeight:800}}>{x.label}</div><div style={{fontSize:12,opacity:0.65}}>{x.desc}</div></div></B>))}</S>
{ok&&<button onClick={gen} style={{width:"100%",padding:"16px",borderRadius:16,border:"none",background:"linear-gradient(135deg,#e65100,#ff8a65)",color:"#fff",fontFamily:"'Jua',cursive",fontSize:20,cursor:"pointer",marginBottom:24,boxShadow:"0 4px 20px rgba(230,81,0,0.3)"}}>🥗 일주일 식단 만들기!</button>}
{wp&&<div ref={ref}>
<button
  onClick={() => downloadPDF(ref.current, 'meal-prep-plan.pdf')}
  style={{
    width: "100%",
    marginBottom: 16,
    padding: "14px",
    borderRadius: 14,
    border: "none",
    background: "linear-gradient(135deg, #e65100, #ff8a65)",
    color: "#fff",
    fontWeight: 800,
    fontSize: 15,
    cursor: "pointer",
    fontFamily: "inherit",
    transition: "transform 0.15s",
    boxShadow: "0 4px 15px rgba(230,81,0,0.3)",
  }}
  onMouseOver={(e) => (e.currentTarget.style.transform = "scale(1.02)")}
  onMouseOut={(e) => (e.currentTarget.style.transform = "scale(1)")}
>
  📥 PDF 다운로드
</button>
<div style={{display:"flex",gap:8,marginBottom:16}}><button onClick={()=>sSg(false)} style={{flex:1,padding:"12px",borderRadius:12,border:!sg?"2px solid #e65100":"2px solid #e0e0e0",background:!sg?"#fff3e0":"#fff",fontWeight:800,fontSize:14,color:!sg?"#e65100":"#999",cursor:"pointer",fontFamily:"inherit"}}>📅 식단표</button><button onClick={()=>sSg(true)} style={{flex:1,padding:"12px",borderRadius:12,border:sg?"2px solid #e65100":"2px solid #e0e0e0",background:sg?"#fff3e0":"#fff",fontWeight:800,fontSize:14,color:sg?"#e65100":"#999",cursor:"pointer",fontFamily:"inherit"}}>🛒 장보기 ({gl.length}개)</button></div>
{!sg?wp.map(day=>{const isE=!!ed[day.day];return(<div key={day.day} style={{marginBottom:8}}><div onClick={()=>sE(prev=>({...prev,[day.day]:!prev[day.day]}))} style={{padding:"14px 18px",borderRadius:isE?"14px 14px 0 0":14,background:isE?"#fff3e0":"rgba(255,255,255,0.88)",border:isE?"2px solid #ffcc80":"2px solid rgba(230,81,0,0.06)",borderBottom:isE?"none":undefined,cursor:"pointer",display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><span style={{fontWeight:800,color:isE?"#e65100":"#555",fontSize:15}}>{day.day}요일</span>{!isE&&<span style={{fontSize:12,color:"#bbb",marginLeft:10}}>{day.breakfast?.name} · {day.lunch?.name} · {day.dinner?.name}</span>}</div><span style={{color:"#ccc",transform:isE?"rotate(180deg)":"rotate(0)",transition:"transform 0.2s"}}>▼</span></div>
{isE&&<div style={{border:"2px solid #ffcc80",borderTop:"none",borderRadius:"0 0 14px 14px",padding:"16px 18px",background:"#fffaf3"}}>{[{l:"🌅 아침",m:day.breakfast},{l:"☀️ 점심",m:day.lunch},{l:"🌙 저녁",m:day.dinner}].map(({l,m})=>m&&<div key={l} style={{marginBottom:16,padding:"14px 16px",background:"#fff",borderRadius:12,border:"1.5px solid #f0f0f0"}}><div style={{fontSize:12,color:"#e65100",fontWeight:800,marginBottom:4}}>{l}</div><div style={{fontWeight:800,color:"#333",fontSize:16,marginBottom:6}}>{m.name}</div><div style={{display:"flex",gap:12,flexWrap:"wrap",marginBottom:8}}><span style={{fontSize:12,color:"#888"}}>⏱️ {m.time}</span><span style={{fontSize:12,color:"#888"}}>🔥 {m.cal}kcal</span><span style={{fontSize:12,color:"#888"}}>💪 {m.protein}</span></div>{m.seasonal?.length>0&&<div style={{fontSize:11,color:"#43a047",fontWeight:700,marginBottom:6}}>🌱 제철: {m.seasonal.join(", ")}</div>}<div style={{fontSize:13,color:"#555",lineHeight:1.7,marginBottom:8}}><strong>만들기:</strong> {m.how}</div><div style={{fontSize:12,color:"#999"}}><strong>재료:</strong> {m.ing?.join(", ")}</div></div>)}</div>}</div>)})
:<div style={{background:"rgba(255,255,255,0.9)",borderRadius:18,padding:"22px",border:"2px solid #ffcc80"}}><h3 style={{fontFamily:"'Jua',cursive",color:"#e65100",margin:"0 0 16px",fontSize:18}}>🛒 장보기 리스트</h3>{gl.map((item,i)=>{const k=`g-${i}`;const d=ch[k];return(<div key={i} onClick={()=>sCh(p=>({...p,[k]:!p[k]}))} style={{display:"flex",alignItems:"center",gap:10,padding:"10px 14px",borderRadius:10,background:d?"#e8f5e9":"#fafafa",cursor:"pointer",marginBottom:4,border:d?"1.5px solid #a5d6a7":"1.5px solid transparent"}}><div style={{width:20,height:20,borderRadius:5,border:d?"2px solid #66bb6a":"2px solid #ddd",background:d?"#66bb6a":"#fff",display:"flex",alignItems:"center",justifyContent:"center",fontSize:12,color:"#fff",fontWeight:800,flexShrink:0}}>{d?"✓":""}</div><span style={{fontSize:14,color:d?"#999":"#444",textDecoration:d?"line-through":"none",fontWeight:d?400:600,flex:1}}>{item.name}</span>{item.count>1&&<span style={{fontSize:11,color:"#bbb",fontWeight:700}}>×{item.count}끼</span>}</div>)})}</div>}
</div>}
<div style={{textAlign:"center",marginTop:48,padding:"20px 0",color:"#ffcc80",fontSize:13}}><div style={{fontSize:24,marginBottom:8}}>🥗🍓🌿</div>봄 식단 플래너 — 제철 먹고, 시간 아끼고!</div></div></div>);}
function S({n,t,c,children}){return(<div style={{background:"rgba(255,255,255,0.85)",borderRadius:20,padding:"22px 24px",marginBottom:20,border:"2px solid rgba(230,81,0,0.08)"}}><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:14}}><div style={{width:28,height:28,borderRadius:"50%",background:`linear-gradient(135deg,${c},#ff8a65)`,color:"#fff",fontWeight:800,fontSize:14,display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}>{n}</div><h3 style={{margin:0,color:c,fontWeight:800,fontSize:16}}>{t}</h3></div><div style={{display:"flex",flexDirection:"column",gap:10}}>{children}</div></div>);}
function B({a,o,children,c,w}){return(<button onClick={o} style={{padding:w?"14px 18px":"14px 10px",borderRadius:14,border:a?`2px solid ${c}`:"2px solid #e0e0e0",background:a?`${c}10`:"rgba(255,255,255,0.85)",color:a?c:"#777",fontWeight:700,fontSize:13,cursor:"pointer",fontFamily:"inherit",textAlign:w?"left":"center",display:w?"flex":"block",alignItems:"center"}}>{children}</button>);}
