'use client';
import { useState, useRef } from "react";
const DIETS=[{id:"none",label:"제한 없음",emoji:"🍽️"},{id:"vegetarian",label:"채식",emoji:"🥦"},{id:"lowcarb",label:"저탄고지",emoji:"🥩"},{id:"diet",label:"다이어트",emoji:"⚖️"}];
const HH=[{id:"1",label:"1인",emoji:"🧑"},{id:"2",label:"2인",emoji:"👫"},{id:"4",label:"가족(3-4인)",emoji:"👨‍👩‍👧"}];
const COOK=[{id:"minimal",label:"간단하게",emoji:"⚡",desc:"15분 이내, 조립 위주"},{id:"moderate",label:"보통",emoji:"🍳",desc:"30분, 제대로 요리"},{id:"ambitious",label:"요리 좋아해요",emoji:"👨‍🍳",desc:"45분+, 본격 요리"}];
const SPRING_PRODUCE="봄 제철: 냉이, 달래, 두릅, 취나물, 미나리, 봄동, 쑥, 딸기, 매실, 봄 양배추";
const MEALS={none:{minimal:{breakfasts:[{name:"아보카도 토스트 + 계란",time:"5분",cal:350,protein:"14g",seasonal:["달걀"],ing:["식빵","아보카도","달걀","소금","후추"],how:"토스트 굽기. 아보카도 으깨서 올리기. 프라이 또는 반숙 얹기."},{name:"그릭요거트 과일 파르페",time:"3분",cal:320,protein:"18g",seasonal:["딸기"],ing:["그릭요거트","그래놀라","딸기","꿀"],how:"요거트, 그래놀라, 딸기 순서로 레이어. 꿀 뿌리기."},{name:"참치 주먹밥",time:"10분",cal:380,protein:"20g",seasonal:[],ing:["밥","참치캔","마요네즈","김","깨"],how:"참치+마요 섞기. 밥에 넣고 삼각형으로 뭉치기. 김 감싸기."},{name:"바나나 땅콩버터 스무디",time:"3분",cal:400,protein:"16g",seasonal:[],ing:["바나나","땅콩버터","우유","오트"],how:"전부 블렌더에 갈기."}],
lunches:[{name:"봄동 비빔밥",time:"15분",cal:450,protein:"18g",seasonal:["봄동","달래"],ing:["밥","봄동","달래","고추장","참기름","계란","당근"],how:"봄동, 달래, 당근 손질. 밥 위에 올리고 계란 프라이 얹기. 고추장+참기름."},{name:"닭가슴살 샐러드 랩",time:"10분",cal:380,protein:"28g",seasonal:["봄 양배추"],ing:["토르티야","닭가슴살(삶은것)","양배추","당근","소스"],how:"닭가슴살 찢기. 채소와 소스 넣고 말기."},{name:"미나리 된장국 + 주먹밥",time:"12분",cal:350,protein:"15g",seasonal:["미나리"],ing:["된장","미나리","두부","파","멸치육수","밥"],how:"멸치육수에 된장 풀기. 두부, 미나리 넣고 끓이기. 주먹밥과 함께."},{name:"참치김치볶음밥",time:"10분",cal:420,protein:"22g",seasonal:[],ing:["밥","참치캔","김치","계란","참기름","김가루"],how:"팬에 김치 볶다가 참치, 밥 넣고 볶기. 계란 프라이 올리고 김가루."}],
dinners:[{name:"봄나물 제육볶음",time:"15분",cal:480,protein:"28g",seasonal:["취나물","미나리"],ing:["돼지고기","고추장","간장","마늘","양파","취나물","밥"],how:"돼지고기 양념해서 볶기. 양파, 마늘 함께. 봄나물 곁들이기."},{name:"연어 미나리 덮밥",time:"12분",cal:500,protein:"32g",seasonal:["미나리"],ing:["연어","미나리","밥","간장","와사비","아보카도"],how:"연어 팬에 굽기 4분씩. 밥 위에 미나리, 연어, 아보카도. 간장 와사비 소스."},{name:"순두부찌개 + 밥",time:"15분",cal:380,protein:"22g",seasonal:["쪽파"],ing:["순두부","김치","돼지고기","계란","쪽파","고춧가루","밥"],how:"돼지고기 볶다가 김치 넣기. 물 붓고 순두부 넣기. 계란 깨넣고 쪽파."},{name:"원팬 닭볶음탕",time:"15분 준비",cal:520,protein:"34g",seasonal:["감자","당근"],ing:["닭","감자","당근","양파","고추장","간장","마늘"],how:"닭, 감자, 당근, 양파 냄비에. 양념장 붓고 끓이기 25분."}]},
moderate:{breakfasts:[{name:"봄나물 프리타타",time:"25분",cal:340,protein:"22g",seasonal:["달래","쑥"],ing:["달걀8개","달래","쑥","치즈","올리브오일"],how:"달래, 쑥 볶기. 달걀 풀어 붓기. 치즈 올리고 오븐 200도 15분."},{name:"딸기 리코타 토스트",time:"10분",cal:360,protein:"14g",seasonal:["딸기"],ing:["식빵","리코타치즈","딸기","꿀","민트"],how:"두꺼운 토스트에 리코타 바르기. 딸기 올리고 꿀, 민트."},{name:"시금치 계란 볶음밥",time:"10분",cal:400,protein:"20g",seasonal:["시금치"],ing:["밥","시금치","계란","참기름","소금"],how:"시금치 볶다가 밥 넣고 볶기. 계란 스크램블 섞기. 참기름."}],
lunches:[{name:"냉이 된장찌개",time:"25분",cal:320,protein:"16g",seasonal:["냉이"],ing:["냉이","된장","두부","감자","호박","멸치육수"],how:"멸치육수에 감자, 호박 끓이기. 된장 풀고 두부, 냉이 넣기."},{name:"봄 비빔국수",time:"15분",cal:420,protein:"15g",seasonal:["열무","오이"],ing:["소면","열무김치","오이","고추장","식초","설탕","깨"],how:"소면 삶아 찬물에 헹구기. 양념장 만들어 비비기. 열무김치, 오이 올리기."},{name:"두릅 삼겹살 구이",time:"20분",cal:500,protein:"24g",seasonal:["두릅"],ing:["삼겹살","두릅","쌈장","상추","마늘"],how:"삼겹살 구워서 두릅과 함께 상추쌈. 쌈장 필수!"}],
dinners:[{name:"봄 해물파전",time:"25분",cal:450,protein:"22g",seasonal:["쪽파"],ing:["쪽파","해물믹스","부침가루","달걀","간장양념장"],how:"부침가루+물+달걀 반죽. 쪽파 길게, 해물 올리고 부치기. 양념장과."},{name:"미나리 삼겹살 찜",time:"30분",cal:520,protein:"30g",seasonal:["미나리"],ing:["삼겹살","미나리","마늘","된장","고추"],how:"삼겹살 삶기. 된장 양념 만들기. 미나리와 함께 찜 또는 쌈으로."},{name:"봄 닭개장",time:"30분",cal:480,protein:"32g",seasonal:["취나물","미나리"],ing:["닭가슴살","취나물","미나리","고춧가루","마늘","대파","밥"],how:"닭 삶아 찢기. 육수에 양념하고 나물 넣어 끓이기. 밥과 함께."}]}
}};
function getMeals(d,c){return MEALS[d]?.[c]||MEALS.none?.minimal||{breakfasts:[],lunches:[],dinners:[]};}
function genWeek(meals){const days=["월","화","수","목","금","토","일"];const{breakfasts:b=[],lunches:l=[],dinners:d=[]}=meals;return days.map((day,i)=>({day,breakfast:b[i%b.length],lunch:l[i%l.length],dinner:d[i%d.length]}));}
function buildGrocery(wp){const all={};wp.forEach(d=>{[d.breakfast,d.lunch,d.dinner].forEach(m=>{m?.ing?.forEach(i=>{const k=i.toLowerCase();all[k]=(all[k]||0)+1;});});});return Object.entries(all).sort((a,b)=>b[1]-a[1]).map(([n,c])=>({name:n,count:c}));}
export default function MealPrepKR(){const[diet,sD]=useState("");const[hh,sH]=useState("");const[cook,sC]=useState("");const[wp,sW]=useState(null);const[gl,sG]=useState([]);const[ed,sE]=useState(null);const[ch,sCh]=useState({});const[sg,sSg]=useState(false);const ref=useRef(null);
const gen=()=>{const m=getMeals(diet,cook);const w=genWeek(m);sW(w);sG(buildGrocery(w));sCh({});sE("월");sSg(false);setTimeout(()=>ref.current?.scrollIntoView({behavior:"smooth"}),150);};
const ok=diet&&hh&&cook;
return(<div style={{minHeight:"100vh",background:"linear-gradient(160deg,#e8f5e9 0%,#fffde7 30%,#fff3e0 60%,#fce4ec 100%)",fontFamily:"'Noto Sans KR',sans-serif",overflow:"hidden"}}><link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@400;600;700;800&family=Jua&display=swap" rel="stylesheet"/>
<div style={{maxWidth:780,margin:"0 auto",padding:"32px 20px",position:"relative",zIndex:1}}>
<div style={{textAlign:"center",marginBottom:36}}><div style={{fontSize:44,marginBottom:8}}>🥗🍓🌿</div><h1 style={{fontFamily:"'Jua',cursive",fontSize:"clamp(26px,5vw,38px)",color:"#e65100",margin:"0 0 8px"}}>봄 식단 플래너</h1><p style={{color:"#ff8a65",fontSize:15,margin:0,fontWeight:600}}>제철 재료로 일주일 식단, 결정 피로 제로!</p></div>
<div style={{background:"rgba(255,255,255,0.85)",borderRadius:16,padding:"16px 20px",marginBottom:20,border:"2px solid #c8e6c9"}}><div style={{fontWeight:800,color:"#2e7d32",fontSize:14,marginBottom:6}}>🌱 {SPRING_PRODUCE}</div></div>
<S n="1" t="식단 유형?" c="#e65100"><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(130px,1fr))",gap:10}}>{DIETS.map(x=>(<B key={x.id} a={diet===x.id} o={()=>sD(x.id)} c="#e65100"><div style={{fontSize:22}}>{x.emoji}</div><div style={{fontWeight:700,fontSize:12}}>{x.label}</div></B>))}</div></S>
<S n="2" t="몇 인분?" c="#e65100"><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:10}}>{HH.map(x=>(<B key={x.id} a={hh===x.id} o={()=>sH(x.id)} c="#e65100"><div style={{fontSize:22}}>{x.emoji}</div><div style={{fontWeight:800,fontSize:13}}>{x.label}</div></B>))}</div></S>
<S n="3" t="요리 수준?" c="#e65100">{COOK.map(x=>(<B key={x.id} a={cook===x.id} o={()=>sC(x.id)} c="#e65100" w><span style={{fontSize:22,marginRight:12}}>{x.emoji}</span><div><div style={{fontWeight:800}}>{x.label}</div><div style={{fontSize:12,opacity:0.65}}>{x.desc}</div></div></B>))}</S>
{ok&&<button onClick={gen} style={{width:"100%",padding:"16px",borderRadius:16,border:"none",background:"linear-gradient(135deg,#e65100,#ff8a65)",color:"#fff",fontFamily:"'Jua',cursive",fontSize:20,cursor:"pointer",marginBottom:24,boxShadow:"0 4px 20px rgba(230,81,0,0.3)"}}>🥗 일주일 식단 만들기!</button>}
{wp&&<div ref={ref}>
<div style={{display:"flex",gap:8,marginBottom:16}}><button onClick={()=>sSg(false)} style={{flex:1,padding:"12px",borderRadius:12,border:!sg?"2px solid #e65100":"2px solid #e0e0e0",background:!sg?"#fff3e0":"#fff",fontWeight:800,fontSize:14,color:!sg?"#e65100":"#999",cursor:"pointer",fontFamily:"inherit"}}>📅 식단표</button><button onClick={()=>sSg(true)} style={{flex:1,padding:"12px",borderRadius:12,border:sg?"2px solid #e65100":"2px solid #e0e0e0",background:sg?"#fff3e0":"#fff",fontWeight:800,fontSize:14,color:sg?"#e65100":"#999",cursor:"pointer",fontFamily:"inherit"}}>🛒 장보기 ({gl.length}개)</button></div>
{!sg?wp.map(day=>{const isE=ed===day.day;return(<div key={day.day} style={{marginBottom:8}}><div onClick={()=>sE(isE?null:day.day)} style={{padding:"14px 18px",borderRadius:isE?"14px 14px 0 0":14,background:isE?"#fff3e0":"rgba(255,255,255,0.88)",border:isE?"2px solid #ffcc80":"2px solid rgba(230,81,0,0.06)",borderBottom:isE?"none":undefined,cursor:"pointer",display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><span style={{fontWeight:800,color:isE?"#e65100":"#555",fontSize:15}}>{day.day}요일</span>{!isE&&<span style={{fontSize:12,color:"#bbb",marginLeft:10}}>{day.breakfast?.name} · {day.lunch?.name} · {day.dinner?.name}</span>}</div><span style={{color:"#ccc",transform:isE?"rotate(180deg)":"rotate(0)",transition:"transform 0.2s"}}>▼</span></div>
{isE&&<div style={{border:"2px solid #ffcc80",borderTop:"none",borderRadius:"0 0 14px 14px",padding:"16px 18px",background:"#fffaf3"}}>{[{l:"🌅 아침",m:day.breakfast},{l:"☀️ 점심",m:day.lunch},{l:"🌙 저녁",m:day.dinner}].map(({l,m})=>m&&<div key={l} style={{marginBottom:16,padding:"14px 16px",background:"#fff",borderRadius:12,border:"1.5px solid #f0f0f0"}}><div style={{fontSize:12,color:"#e65100",fontWeight:800,marginBottom:4}}>{l}</div><div style={{fontWeight:800,color:"#333",fontSize:16,marginBottom:6}}>{m.name}</div><div style={{display:"flex",gap:12,flexWrap:"wrap",marginBottom:8}}><span style={{fontSize:12,color:"#888"}}>⏱️ {m.time}</span><span style={{fontSize:12,color:"#888"}}>🔥 {m.cal}kcal</span><span style={{fontSize:12,color:"#888"}}>💪 {m.protein}</span></div>{m.seasonal?.length>0&&<div style={{fontSize:11,color:"#43a047",fontWeight:700,marginBottom:6}}>🌱 제철: {m.seasonal.join(", ")}</div>}<div style={{fontSize:13,color:"#555",lineHeight:1.7,marginBottom:8}}><strong>만들기:</strong> {m.how}</div><div style={{fontSize:12,color:"#999"}}><strong>재료:</strong> {m.ing?.join(", ")}</div></div>)}</div>}</div>)})
:<div style={{background:"rgba(255,255,255,0.9)",borderRadius:18,padding:"22px",border:"2px solid #ffcc80"}}><h3 style={{fontFamily:"'Jua',cursive",color:"#e65100",margin:"0 0 16px",fontSize:18}}>🛒 장보기 리스트</h3>{gl.map((item,i)=>{const k=`g-${i}`;const d=ch[k];return(<div key={i} onClick={()=>sCh(p=>({...p,[k]:!p[k]}))} style={{display:"flex",alignItems:"center",gap:10,padding:"10px 14px",borderRadius:10,background:d?"#e8f5e9":"#fafafa",cursor:"pointer",marginBottom:4,border:d?"1.5px solid #a5d6a7":"1.5px solid transparent"}}><div style={{width:20,height:20,borderRadius:5,border:d?"2px solid #66bb6a":"2px solid #ddd",background:d?"#66bb6a":"#fff",display:"flex",alignItems:"center",justifyContent:"center",fontSize:12,color:"#fff",fontWeight:800,flexShrink:0}}>{d?"✓":""}</div><span style={{fontSize:14,color:d?"#999":"#444",textDecoration:d?"line-through":"none",fontWeight:d?400:600,flex:1}}>{item.name}</span>{item.count>1&&<span style={{fontSize:11,color:"#bbb",fontWeight:700}}>×{item.count}끼</span>}</div>)})}</div>}
</div>}
<div style={{textAlign:"center",marginTop:48,padding:"20px 0",color:"#ffcc80",fontSize:13}}><div style={{fontSize:24,marginBottom:8}}>🥗🍓🌿</div>봄 식단 플래너 — 제철 먹고, 시간 아끼고!</div></div></div>);}
function S({n,t,c,children}){return(<div style={{background:"rgba(255,255,255,0.85)",borderRadius:20,padding:"22px 24px",marginBottom:20,border:"2px solid rgba(230,81,0,0.08)"}}><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:14}}><div style={{width:28,height:28,borderRadius:"50%",background:`linear-gradient(135deg,${c},#ff8a65)`,color:"#fff",fontWeight:800,fontSize:14,display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}>{n}</div><h3 style={{margin:0,color:c,fontWeight:800,fontSize:16}}>{t}</h3></div><div style={{display:"flex",flexDirection:"column",gap:10}}>{children}</div></div>);}
function B({a,o,children,c,w}){return(<button onClick={o} style={{padding:w?"14px 18px":"14px 10px",borderRadius:14,border:a?`2px solid ${c}`:"2px solid #e0e0e0",background:a?`${c}10`:"rgba(255,255,255,0.85)",color:a?c:"#777",fontWeight:700,fontSize:13,cursor:"pointer",fontFamily:"inherit",textAlign:w?"left":"center",display:w?"flex":"block",alignItems:"center"}}>{children}</button>);}
